// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockClipboard is an autogenerated mock type for the Clipboard type
type MockClipboard struct {
	mock.Mock
}

type MockClipboard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClipboard) EXPECT() *MockClipboard_Expecter {
	return &MockClipboard_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function with given fields: text
func (_m *MockClipboard) Copy(text string) error {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClipboard_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockClipboard_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - text string
func (_e *MockClipboard_Expecter) Copy(text interface{}) *MockClipboard_Copy_Call {
	return &MockClipboard_Copy_Call{Call: _e.mock.On("Copy", text)}
}

func (_c *MockClipboard_Copy_Call) Run(run func(text string)) *MockClipboard_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClipboard_Copy_Call) Return(_a0 error) *MockClipboard_Copy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClipboard_Copy_Call) RunAndReturn(run func(string) error) *MockClipboard_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClipboard creates a new instance of MockClipboard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClipboard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClipboard {
	mock := &MockClipboard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
