// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	beads "github.com/zjrosen/perles/internal/beads"
)

// MockBeadsClient is an autogenerated mock type for the BeadsClient type
type MockBeadsClient struct {
	mock.Mock
}

type MockBeadsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeadsClient) EXPECT() *MockBeadsClient_Expecter {
	return &MockBeadsClient_Expecter{mock: &_m.Mock}
}

// GetComments provides a mock function with given fields: issueID
func (_m *MockBeadsClient) GetComments(issueID string) ([]beads.Comment, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []beads.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]beads.Comment, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) []beads.Comment); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]beads.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBeadsClient_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockBeadsClient_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - issueID string
func (_e *MockBeadsClient_Expecter) GetComments(issueID interface{}) *MockBeadsClient_GetComments_Call {
	return &MockBeadsClient_GetComments_Call{Call: _e.mock.On("GetComments", issueID)}
}

func (_c *MockBeadsClient_GetComments_Call) Run(run func(issueID string)) *MockBeadsClient_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBeadsClient_GetComments_Call) Return(_a0 []beads.Comment, _a1 error) *MockBeadsClient_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBeadsClient_GetComments_Call) RunAndReturn(run func(string) ([]beads.Comment, error)) *MockBeadsClient_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with no fields
func (_m *MockBeadsClient) Version() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBeadsClient_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockBeadsClient_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockBeadsClient_Expecter) Version() *MockBeadsClient_Version_Call {
	return &MockBeadsClient_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockBeadsClient_Version_Call) Run(run func()) *MockBeadsClient_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBeadsClient_Version_Call) Return(_a0 string, _a1 error) *MockBeadsClient_Version_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBeadsClient_Version_Call) RunAndReturn(run func() (string, error)) *MockBeadsClient_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBeadsClient creates a new instance of MockBeadsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeadsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeadsClient {
	mock := &MockBeadsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
