// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/zjrosen/perles/internal/orchestration/client"

	mock "github.com/stretchr/testify/mock"
)

// MockHeadlessClient is an autogenerated mock type for the HeadlessClient type
type MockHeadlessClient struct {
	mock.Mock
}

type MockHeadlessClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeadlessClient) EXPECT() *MockHeadlessClient_Expecter {
	return &MockHeadlessClient_Expecter{mock: &_m.Mock}
}

// Spawn provides a mock function with given fields: ctx, cfg
func (_m *MockHeadlessClient) Spawn(ctx context.Context, cfg client.Config) (client.HeadlessProcess, error) {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Spawn")
	}

	var r0 client.HeadlessProcess
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Config) (client.HeadlessProcess, error)); ok {
		return rf(ctx, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Config) client.HeadlessProcess); ok {
		r0 = rf(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.HeadlessProcess)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Config) error); ok {
		r1 = rf(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeadlessClient_Spawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spawn'
type MockHeadlessClient_Spawn_Call struct {
	*mock.Call
}

// Spawn is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg client.Config
func (_e *MockHeadlessClient_Expecter) Spawn(ctx interface{}, cfg interface{}) *MockHeadlessClient_Spawn_Call {
	return &MockHeadlessClient_Spawn_Call{Call: _e.mock.On("Spawn", ctx, cfg)}
}

func (_c *MockHeadlessClient_Spawn_Call) Run(run func(ctx context.Context, cfg client.Config)) *MockHeadlessClient_Spawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Config))
	})
	return _c
}

func (_c *MockHeadlessClient_Spawn_Call) Return(_a0 client.HeadlessProcess, _a1 error) *MockHeadlessClient_Spawn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeadlessClient_Spawn_Call) RunAndReturn(run func(context.Context, client.Config) (client.HeadlessProcess, error)) *MockHeadlessClient_Spawn_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockHeadlessClient) Type() client.ClientType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 client.ClientType
	if rf, ok := ret.Get(0).(func() client.ClientType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(client.ClientType)
	}

	return r0
}

// MockHeadlessClient_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockHeadlessClient_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockHeadlessClient_Expecter) Type() *MockHeadlessClient_Type_Call {
	return &MockHeadlessClient_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockHeadlessClient_Type_Call) Run(run func()) *MockHeadlessClient_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessClient_Type_Call) Return(_a0 client.ClientType) *MockHeadlessClient_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessClient_Type_Call) RunAndReturn(run func() client.ClientType) *MockHeadlessClient_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHeadlessClient creates a new instance of MockHeadlessClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeadlessClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeadlessClient {
	mock := &MockHeadlessClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
