// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/zjrosen/perles/internal/orchestration/client"
)

// MockHeadlessProcess is an autogenerated mock type for the HeadlessProcess type
type MockHeadlessProcess struct {
	mock.Mock
}

type MockHeadlessProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeadlessProcess) EXPECT() *MockHeadlessProcess_Expecter {
	return &MockHeadlessProcess_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with no fields
func (_m *MockHeadlessProcess) Cancel() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeadlessProcess_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockHeadlessProcess_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) Cancel() *MockHeadlessProcess_Cancel_Call {
	return &MockHeadlessProcess_Cancel_Call{Call: _e.mock.On("Cancel")}
}

func (_c *MockHeadlessProcess_Cancel_Call) Run(run func()) *MockHeadlessProcess_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_Cancel_Call) Return(_a0 error) *MockHeadlessProcess_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_Cancel_Call) RunAndReturn(run func() error) *MockHeadlessProcess_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Errors provides a mock function with no fields
func (_m *MockHeadlessProcess) Errors() <-chan error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// MockHeadlessProcess_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockHeadlessProcess_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) Errors() *MockHeadlessProcess_Errors_Call {
	return &MockHeadlessProcess_Errors_Call{Call: _e.mock.On("Errors")}
}

func (_c *MockHeadlessProcess_Errors_Call) Run(run func()) *MockHeadlessProcess_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_Errors_Call) Return(_a0 <-chan error) *MockHeadlessProcess_Errors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_Errors_Call) RunAndReturn(run func() <-chan error) *MockHeadlessProcess_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function with no fields
func (_m *MockHeadlessProcess) Events() <-chan client.OutputEvent {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan client.OutputEvent
	if rf, ok := ret.Get(0).(func() <-chan client.OutputEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan client.OutputEvent)
		}
	}

	return r0
}

// MockHeadlessProcess_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockHeadlessProcess_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) Events() *MockHeadlessProcess_Events_Call {
	return &MockHeadlessProcess_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *MockHeadlessProcess_Events_Call) Run(run func()) *MockHeadlessProcess_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_Events_Call) Return(_a0 <-chan client.OutputEvent) *MockHeadlessProcess_Events_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_Events_Call) RunAndReturn(run func() <-chan client.OutputEvent) *MockHeadlessProcess_Events_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function with no fields
func (_m *MockHeadlessProcess) IsRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockHeadlessProcess_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockHeadlessProcess_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) IsRunning() *MockHeadlessProcess_IsRunning_Call {
	return &MockHeadlessProcess_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockHeadlessProcess_IsRunning_Call) Run(run func()) *MockHeadlessProcess_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_IsRunning_Call) Return(_a0 bool) *MockHeadlessProcess_IsRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_IsRunning_Call) RunAndReturn(run func() bool) *MockHeadlessProcess_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// PID provides a mock function with no fields
func (_m *MockHeadlessProcess) PID() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PID")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockHeadlessProcess_PID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PID'
type MockHeadlessProcess_PID_Call struct {
	*mock.Call
}

// PID is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) PID() *MockHeadlessProcess_PID_Call {
	return &MockHeadlessProcess_PID_Call{Call: _e.mock.On("PID")}
}

func (_c *MockHeadlessProcess_PID_Call) Run(run func()) *MockHeadlessProcess_PID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_PID_Call) Return(_a0 int) *MockHeadlessProcess_PID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_PID_Call) RunAndReturn(run func() int) *MockHeadlessProcess_PID_Call {
	_c.Call.Return(run)
	return _c
}

// SessionRef provides a mock function with no fields
func (_m *MockHeadlessProcess) SessionRef() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SessionRef")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHeadlessProcess_SessionRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionRef'
type MockHeadlessProcess_SessionRef_Call struct {
	*mock.Call
}

// SessionRef is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) SessionRef() *MockHeadlessProcess_SessionRef_Call {
	return &MockHeadlessProcess_SessionRef_Call{Call: _e.mock.On("SessionRef")}
}

func (_c *MockHeadlessProcess_SessionRef_Call) Run(run func()) *MockHeadlessProcess_SessionRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_SessionRef_Call) Return(_a0 string) *MockHeadlessProcess_SessionRef_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_SessionRef_Call) RunAndReturn(run func() string) *MockHeadlessProcess_SessionRef_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MockHeadlessProcess) Status() client.ProcessStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.ProcessStatus
	if rf, ok := ret.Get(0).(func() client.ProcessStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(client.ProcessStatus)
	}

	return r0
}

// MockHeadlessProcess_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockHeadlessProcess_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) Status() *MockHeadlessProcess_Status_Call {
	return &MockHeadlessProcess_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockHeadlessProcess_Status_Call) Run(run func()) *MockHeadlessProcess_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_Status_Call) Return(_a0 client.ProcessStatus) *MockHeadlessProcess_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_Status_Call) RunAndReturn(run func() client.ProcessStatus) *MockHeadlessProcess_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with no fields
func (_m *MockHeadlessProcess) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeadlessProcess_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockHeadlessProcess_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) Wait() *MockHeadlessProcess_Wait_Call {
	return &MockHeadlessProcess_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockHeadlessProcess_Wait_Call) Run(run func()) *MockHeadlessProcess_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_Wait_Call) Return(_a0 error) *MockHeadlessProcess_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_Wait_Call) RunAndReturn(run func() error) *MockHeadlessProcess_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// WorkDir provides a mock function with no fields
func (_m *MockHeadlessProcess) WorkDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHeadlessProcess_WorkDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkDir'
type MockHeadlessProcess_WorkDir_Call struct {
	*mock.Call
}

// WorkDir is a helper method to define mock.On call
func (_e *MockHeadlessProcess_Expecter) WorkDir() *MockHeadlessProcess_WorkDir_Call {
	return &MockHeadlessProcess_WorkDir_Call{Call: _e.mock.On("WorkDir")}
}

func (_c *MockHeadlessProcess_WorkDir_Call) Run(run func()) *MockHeadlessProcess_WorkDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeadlessProcess_WorkDir_Call) Return(_a0 string) *MockHeadlessProcess_WorkDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeadlessProcess_WorkDir_Call) RunAndReturn(run func() string) *MockHeadlessProcess_WorkDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHeadlessProcess creates a new instance of MockHeadlessProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeadlessProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeadlessProcess {
	mock := &MockHeadlessProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
