// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	beads "github.com/zjrosen/perles/internal/beads"
)

// MockBeadsExecutor is an autogenerated mock type for the BeadsExecutor type
type MockBeadsExecutor struct {
	mock.Mock
}

type MockBeadsExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeadsExecutor) EXPECT() *MockBeadsExecutor_Expecter {
	return &MockBeadsExecutor_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: issueID, author, text
func (_m *MockBeadsExecutor) AddComment(issueID string, author string, text string) error {
	ret := _m.Called(issueID, author, text)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(issueID, author, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockBeadsExecutor_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - issueID string
//   - author string
//   - text string
func (_e *MockBeadsExecutor_Expecter) AddComment(issueID interface{}, author interface{}, text interface{}) *MockBeadsExecutor_AddComment_Call {
	return &MockBeadsExecutor_AddComment_Call{Call: _e.mock.On("AddComment", issueID, author, text)}
}

func (_c *MockBeadsExecutor_AddComment_Call) Run(run func(issueID string, author string, text string)) *MockBeadsExecutor_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBeadsExecutor_AddComment_Call) Return(_a0 error) *MockBeadsExecutor_AddComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_AddComment_Call) RunAndReturn(run func(string, string, string) error) *MockBeadsExecutor_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// CloseIssue provides a mock function with given fields: issueID, reason
func (_m *MockBeadsExecutor) CloseIssue(issueID string, reason string) error {
	ret := _m.Called(issueID, reason)

	if len(ret) == 0 {
		panic("no return value specified for CloseIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_CloseIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIssue'
type MockBeadsExecutor_CloseIssue_Call struct {
	*mock.Call
}

// CloseIssue is a helper method to define mock.On call
//   - issueID string
//   - reason string
func (_e *MockBeadsExecutor_Expecter) CloseIssue(issueID interface{}, reason interface{}) *MockBeadsExecutor_CloseIssue_Call {
	return &MockBeadsExecutor_CloseIssue_Call{Call: _e.mock.On("CloseIssue", issueID, reason)}
}

func (_c *MockBeadsExecutor_CloseIssue_Call) Run(run func(issueID string, reason string)) *MockBeadsExecutor_CloseIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockBeadsExecutor_CloseIssue_Call) Return(_a0 error) *MockBeadsExecutor_CloseIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_CloseIssue_Call) RunAndReturn(run func(string, string) error) *MockBeadsExecutor_CloseIssue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssues provides a mock function with given fields: issueIDs
func (_m *MockBeadsExecutor) DeleteIssues(issueIDs []string) error {
	ret := _m.Called(issueIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssues")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(issueIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_DeleteIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssues'
type MockBeadsExecutor_DeleteIssues_Call struct {
	*mock.Call
}

// DeleteIssues is a helper method to define mock.On call
//   - issueIDs []string
func (_e *MockBeadsExecutor_Expecter) DeleteIssues(issueIDs interface{}) *MockBeadsExecutor_DeleteIssues_Call {
	return &MockBeadsExecutor_DeleteIssues_Call{Call: _e.mock.On("DeleteIssues", issueIDs)}
}

func (_c *MockBeadsExecutor_DeleteIssues_Call) Run(run func(issueIDs []string)) *MockBeadsExecutor_DeleteIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockBeadsExecutor_DeleteIssues_Call) Return(_a0 error) *MockBeadsExecutor_DeleteIssues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_DeleteIssues_Call) RunAndReturn(run func([]string) error) *MockBeadsExecutor_DeleteIssues_Call {
	_c.Call.Return(run)
	return _c
}

// ReopenIssue provides a mock function with given fields: issueID
func (_m *MockBeadsExecutor) ReopenIssue(issueID string) error {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ReopenIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(issueID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_ReopenIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReopenIssue'
type MockBeadsExecutor_ReopenIssue_Call struct {
	*mock.Call
}

// ReopenIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockBeadsExecutor_Expecter) ReopenIssue(issueID interface{}) *MockBeadsExecutor_ReopenIssue_Call {
	return &MockBeadsExecutor_ReopenIssue_Call{Call: _e.mock.On("ReopenIssue", issueID)}
}

func (_c *MockBeadsExecutor_ReopenIssue_Call) Run(run func(issueID string)) *MockBeadsExecutor_ReopenIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBeadsExecutor_ReopenIssue_Call) Return(_a0 error) *MockBeadsExecutor_ReopenIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_ReopenIssue_Call) RunAndReturn(run func(string) error) *MockBeadsExecutor_ReopenIssue_Call {
	_c.Call.Return(run)
	return _c
}

// SetLabels provides a mock function with given fields: issueID, labels
func (_m *MockBeadsExecutor) SetLabels(issueID string, labels []string) error {
	ret := _m.Called(issueID, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabels")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(issueID, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type MockBeadsExecutor_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - issueID string
//   - labels []string
func (_e *MockBeadsExecutor_Expecter) SetLabels(issueID interface{}, labels interface{}) *MockBeadsExecutor_SetLabels_Call {
	return &MockBeadsExecutor_SetLabels_Call{Call: _e.mock.On("SetLabels", issueID, labels)}
}

func (_c *MockBeadsExecutor_SetLabels_Call) Run(run func(issueID string, labels []string)) *MockBeadsExecutor_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockBeadsExecutor_SetLabels_Call) Return(_a0 error) *MockBeadsExecutor_SetLabels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_SetLabels_Call) RunAndReturn(run func(string, []string) error) *MockBeadsExecutor_SetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// ShowIssue provides a mock function with given fields: issueID
func (_m *MockBeadsExecutor) ShowIssue(issueID string) (*beads.Issue, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ShowIssue")
	}

	var r0 *beads.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*beads.Issue, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) *beads.Issue); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*beads.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBeadsExecutor_ShowIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowIssue'
type MockBeadsExecutor_ShowIssue_Call struct {
	*mock.Call
}

// ShowIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockBeadsExecutor_Expecter) ShowIssue(issueID interface{}) *MockBeadsExecutor_ShowIssue_Call {
	return &MockBeadsExecutor_ShowIssue_Call{Call: _e.mock.On("ShowIssue", issueID)}
}

func (_c *MockBeadsExecutor_ShowIssue_Call) Run(run func(issueID string)) *MockBeadsExecutor_ShowIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBeadsExecutor_ShowIssue_Call) Return(_a0 *beads.Issue, _a1 error) *MockBeadsExecutor_ShowIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBeadsExecutor_ShowIssue_Call) RunAndReturn(run func(string) (*beads.Issue, error)) *MockBeadsExecutor_ShowIssue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriority provides a mock function with given fields: issueID, priority
func (_m *MockBeadsExecutor) UpdatePriority(issueID string, priority beads.Priority) error {
	ret := _m.Called(issueID, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, beads.Priority) error); ok {
		r0 = rf(issueID, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_UpdatePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriority'
type MockBeadsExecutor_UpdatePriority_Call struct {
	*mock.Call
}

// UpdatePriority is a helper method to define mock.On call
//   - issueID string
//   - priority beads.Priority
func (_e *MockBeadsExecutor_Expecter) UpdatePriority(issueID interface{}, priority interface{}) *MockBeadsExecutor_UpdatePriority_Call {
	return &MockBeadsExecutor_UpdatePriority_Call{Call: _e.mock.On("UpdatePriority", issueID, priority)}
}

func (_c *MockBeadsExecutor_UpdatePriority_Call) Run(run func(issueID string, priority beads.Priority)) *MockBeadsExecutor_UpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(beads.Priority))
	})
	return _c
}

func (_c *MockBeadsExecutor_UpdatePriority_Call) Return(_a0 error) *MockBeadsExecutor_UpdatePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_UpdatePriority_Call) RunAndReturn(run func(string, beads.Priority) error) *MockBeadsExecutor_UpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: issueID, status
func (_m *MockBeadsExecutor) UpdateStatus(issueID string, status beads.Status) error {
	ret := _m.Called(issueID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, beads.Status) error); ok {
		r0 = rf(issueID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockBeadsExecutor_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - issueID string
//   - status beads.Status
func (_e *MockBeadsExecutor_Expecter) UpdateStatus(issueID interface{}, status interface{}) *MockBeadsExecutor_UpdateStatus_Call {
	return &MockBeadsExecutor_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", issueID, status)}
}

func (_c *MockBeadsExecutor_UpdateStatus_Call) Run(run func(issueID string, status beads.Status)) *MockBeadsExecutor_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(beads.Status))
	})
	return _c
}

func (_c *MockBeadsExecutor_UpdateStatus_Call) Return(_a0 error) *MockBeadsExecutor_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_UpdateStatus_Call) RunAndReturn(run func(string, beads.Status) error) *MockBeadsExecutor_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateType provides a mock function with given fields: issueID, issueType
func (_m *MockBeadsExecutor) UpdateType(issueID string, issueType beads.IssueType) error {
	ret := _m.Called(issueID, issueType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, beads.IssueType) error); ok {
		r0 = rf(issueID, issueType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBeadsExecutor_UpdateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateType'
type MockBeadsExecutor_UpdateType_Call struct {
	*mock.Call
}

// UpdateType is a helper method to define mock.On call
//   - issueID string
//   - issueType beads.IssueType
func (_e *MockBeadsExecutor_Expecter) UpdateType(issueID interface{}, issueType interface{}) *MockBeadsExecutor_UpdateType_Call {
	return &MockBeadsExecutor_UpdateType_Call{Call: _e.mock.On("UpdateType", issueID, issueType)}
}

func (_c *MockBeadsExecutor_UpdateType_Call) Run(run func(issueID string, issueType beads.IssueType)) *MockBeadsExecutor_UpdateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(beads.IssueType))
	})
	return _c
}

func (_c *MockBeadsExecutor_UpdateType_Call) Return(_a0 error) *MockBeadsExecutor_UpdateType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBeadsExecutor_UpdateType_Call) RunAndReturn(run func(string, beads.IssueType) error) *MockBeadsExecutor_UpdateType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBeadsExecutor creates a new instance of MockBeadsExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeadsExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeadsExecutor {
	mock := &MockBeadsExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
