// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheManager is an autogenerated mock type for the CacheManager type
type MockCacheManager[K comparable, V interface{}] struct {
	mock.Mock
}

type MockCacheManager_Expecter[K comparable, V interface{}] struct {
	mock *mock.Mock
}

func (_m *MockCacheManager[K, V]) EXPECT() *MockCacheManager_Expecter[K, V] {
	return &MockCacheManager_Expecter[K, V]{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, keys
func (_m *MockCacheManager[K, V]) Delete(ctx context.Context, keys ...K) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...K) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheManager_Delete_Call[K comparable, V interface{}] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...K
func (_e *MockCacheManager_Expecter[K, V]) Delete(ctx interface{}, keys ...interface{}) *MockCacheManager_Delete_Call[K, V] {
	return &MockCacheManager_Delete_Call[K, V]{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockCacheManager_Delete_Call[K, V]) Run(run func(ctx context.Context, keys ...K)) *MockCacheManager_Delete_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]K, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(K)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockCacheManager_Delete_Call[K, V]) Return(_a0 error) *MockCacheManager_Delete_Call[K, V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheManager_Delete_Call[K, V]) RunAndReturn(run func(context.Context, ...K) error) *MockCacheManager_Delete_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function with given fields: ctx
func (_m *MockCacheManager[K, V]) Flush(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheManager_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockCacheManager_Flush_Call[K comparable, V interface{}] struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheManager_Expecter[K, V]) Flush(ctx interface{}) *MockCacheManager_Flush_Call[K, V] {
	return &MockCacheManager_Flush_Call[K, V]{Call: _e.mock.On("Flush", ctx)}
}

func (_c *MockCacheManager_Flush_Call[K, V]) Run(run func(ctx context.Context)) *MockCacheManager_Flush_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCacheManager_Flush_Call[K, V]) Return(_a0 error) *MockCacheManager_Flush_Call[K, V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheManager_Flush_Call[K, V]) RunAndReturn(run func(context.Context) error) *MockCacheManager_Flush_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockCacheManager[K, V]) Get(ctx context.Context, key K) (V, bool) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, K) (V, bool)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, K) V); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, K) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCacheManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheManager_Get_Call[K comparable, V interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
func (_e *MockCacheManager_Expecter[K, V]) Get(ctx interface{}, key interface{}) *MockCacheManager_Get_Call[K, V] {
	return &MockCacheManager_Get_Call[K, V]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheManager_Get_Call[K, V]) Run(run func(ctx context.Context, key K)) *MockCacheManager_Get_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(K))
	})
	return _c
}

func (_c *MockCacheManager_Get_Call[K, V]) Return(_a0 V, _a1 bool) *MockCacheManager_Get_Call[K, V] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheManager_Get_Call[K, V]) RunAndReturn(run func(context.Context, K) (V, bool)) *MockCacheManager_Get_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// GetMultiple provides a mock function with given fields: ctx, keys
func (_m *MockCacheManager[K, V]) GetMultiple(ctx context.Context, keys []K) (map[K]V, bool) {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for GetMultiple")
	}

	var r0 map[K]V
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, []K) (map[K]V, bool)); ok {
		return rf(ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []K) map[K]V); ok {
		r0 = rf(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[K]V)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []K) bool); ok {
		r1 = rf(ctx, keys)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCacheManager_GetMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultiple'
type MockCacheManager_GetMultiple_Call[K comparable, V interface{}] struct {
	*mock.Call
}

// GetMultiple is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []K
func (_e *MockCacheManager_Expecter[K, V]) GetMultiple(ctx interface{}, keys interface{}) *MockCacheManager_GetMultiple_Call[K, V] {
	return &MockCacheManager_GetMultiple_Call[K, V]{Call: _e.mock.On("GetMultiple", ctx, keys)}
}

func (_c *MockCacheManager_GetMultiple_Call[K, V]) Run(run func(ctx context.Context, keys []K)) *MockCacheManager_GetMultiple_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]K))
	})
	return _c
}

func (_c *MockCacheManager_GetMultiple_Call[K, V]) Return(_a0 map[K]V, _a1 bool) *MockCacheManager_GetMultiple_Call[K, V] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheManager_GetMultiple_Call[K, V]) RunAndReturn(run func(context.Context, []K) (map[K]V, bool)) *MockCacheManager_GetMultiple_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// GetWithRefresh provides a mock function with given fields: ctx, key, ttl
func (_m *MockCacheManager[K, V]) GetWithRefresh(ctx context.Context, key K, ttl time.Duration) (V, bool) {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GetWithRefresh")
	}

	var r0 V
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, K, time.Duration) (V, bool)); ok {
		return rf(ctx, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, K, time.Duration) V); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, K, time.Duration) bool); ok {
		r1 = rf(ctx, key, ttl)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCacheManager_GetWithRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithRefresh'
type MockCacheManager_GetWithRefresh_Call[K comparable, V interface{}] struct {
	*mock.Call
}

// GetWithRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
//   - ttl time.Duration
func (_e *MockCacheManager_Expecter[K, V]) GetWithRefresh(ctx interface{}, key interface{}, ttl interface{}) *MockCacheManager_GetWithRefresh_Call[K, V] {
	return &MockCacheManager_GetWithRefresh_Call[K, V]{Call: _e.mock.On("GetWithRefresh", ctx, key, ttl)}
}

func (_c *MockCacheManager_GetWithRefresh_Call[K, V]) Run(run func(ctx context.Context, key K, ttl time.Duration)) *MockCacheManager_GetWithRefresh_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(K), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockCacheManager_GetWithRefresh_Call[K, V]) Return(_a0 V, _a1 bool) *MockCacheManager_GetWithRefresh_Call[K, V] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheManager_GetWithRefresh_Call[K, V]) RunAndReturn(run func(context.Context, K, time.Duration) (V, bool)) *MockCacheManager_GetWithRefresh_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockCacheManager[K, V]) Set(ctx context.Context, key K, value V, ttl time.Duration) {
	_m.Called(ctx, key, value, ttl)
}

// MockCacheManager_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheManager_Set_Call[K comparable, V interface{}] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
//   - value V
//   - ttl time.Duration
func (_e *MockCacheManager_Expecter[K, V]) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockCacheManager_Set_Call[K, V] {
	return &MockCacheManager_Set_Call[K, V]{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockCacheManager_Set_Call[K, V]) Run(run func(ctx context.Context, key K, value V, ttl time.Duration)) *MockCacheManager_Set_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(K), args[2].(V), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCacheManager_Set_Call[K, V]) Return() *MockCacheManager_Set_Call[K, V] {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheManager_Set_Call[K, V]) RunAndReturn(run func(context.Context, K, V, time.Duration)) *MockCacheManager_Set_Call[K, V] {
	_c.Run(run)
	return _c
}

// NewMockCacheManager creates a new instance of MockCacheManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheManager[K comparable, V interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheManager[K, V] {
	mock := &MockCacheManager[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
