// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	beads "perles/internal/beads"

	mock "github.com/stretchr/testify/mock"
)

// MockBQLExecutor is an autogenerated mock type for the BQLExecutor type
type MockBQLExecutor struct {
	mock.Mock
}

type MockBQLExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBQLExecutor) EXPECT() *MockBQLExecutor_Expecter {
	return &MockBQLExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: query
func (_m *MockBQLExecutor) Execute(query string) ([]beads.Issue, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []beads.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]beads.Issue, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []beads.Issue); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]beads.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBQLExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockBQLExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - query string
func (_e *MockBQLExecutor_Expecter) Execute(query interface{}) *MockBQLExecutor_Execute_Call {
	return &MockBQLExecutor_Execute_Call{Call: _e.mock.On("Execute", query)}
}

func (_c *MockBQLExecutor_Execute_Call) Run(run func(query string)) *MockBQLExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBQLExecutor_Execute_Call) Return(_a0 []beads.Issue, _a1 error) *MockBQLExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBQLExecutor_Execute_Call) RunAndReturn(run func(string) ([]beads.Issue, error)) *MockBQLExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBQLExecutor creates a new instance of MockBQLExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBQLExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBQLExecutor {
	mock := &MockBQLExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
