// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	git "github.com/zjrosen/perles/internal/git"
)

// MockGitExecutor is an autogenerated mock type for the GitExecutor type
type MockGitExecutor struct {
	mock.Mock
}

type MockGitExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitExecutor) EXPECT() *MockGitExecutor_Expecter {
	return &MockGitExecutor_Expecter{mock: &_m.Mock}
}

// BranchExists provides a mock function with given fields: name
func (_m *MockGitExecutor) BranchExists(name string) bool {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for BranchExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockGitExecutor_BranchExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BranchExists'
type MockGitExecutor_BranchExists_Call struct {
	*mock.Call
}

// BranchExists is a helper method to define mock.On call
//   - name string
func (_e *MockGitExecutor_Expecter) BranchExists(name interface{}) *MockGitExecutor_BranchExists_Call {
	return &MockGitExecutor_BranchExists_Call{Call: _e.mock.On("BranchExists", name)}
}

func (_c *MockGitExecutor_BranchExists_Call) Run(run func(name string)) *MockGitExecutor_BranchExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_BranchExists_Call) Return(_a0 bool) *MockGitExecutor_BranchExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitExecutor_BranchExists_Call) RunAndReturn(run func(string) bool) *MockGitExecutor_BranchExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorktree provides a mock function with given fields: path, newBranch, baseBranch
func (_m *MockGitExecutor) CreateWorktree(path string, newBranch string, baseBranch string) error {
	ret := _m.Called(path, newBranch, baseBranch)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorktree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(path, newBranch, baseBranch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitExecutor_CreateWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorktree'
type MockGitExecutor_CreateWorktree_Call struct {
	*mock.Call
}

// CreateWorktree is a helper method to define mock.On call
//   - path string
//   - newBranch string
//   - baseBranch string
func (_e *MockGitExecutor_Expecter) CreateWorktree(path interface{}, newBranch interface{}, baseBranch interface{}) *MockGitExecutor_CreateWorktree_Call {
	return &MockGitExecutor_CreateWorktree_Call{Call: _e.mock.On("CreateWorktree", path, newBranch, baseBranch)}
}

func (_c *MockGitExecutor_CreateWorktree_Call) Run(run func(path string, newBranch string, baseBranch string)) *MockGitExecutor_CreateWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGitExecutor_CreateWorktree_Call) Return(_a0 error) *MockGitExecutor_CreateWorktree_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitExecutor_CreateWorktree_Call) RunAndReturn(run func(string, string, string) error) *MockGitExecutor_CreateWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// DetermineWorktreePath provides a mock function with given fields: sessionID
func (_m *MockGitExecutor) DetermineWorktreePath(sessionID string) (string, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DetermineWorktreePath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_DetermineWorktreePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetermineWorktreePath'
type MockGitExecutor_DetermineWorktreePath_Call struct {
	*mock.Call
}

// DetermineWorktreePath is a helper method to define mock.On call
//   - sessionID string
func (_e *MockGitExecutor_Expecter) DetermineWorktreePath(sessionID interface{}) *MockGitExecutor_DetermineWorktreePath_Call {
	return &MockGitExecutor_DetermineWorktreePath_Call{Call: _e.mock.On("DetermineWorktreePath", sessionID)}
}

func (_c *MockGitExecutor_DetermineWorktreePath_Call) Run(run func(sessionID string)) *MockGitExecutor_DetermineWorktreePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_DetermineWorktreePath_Call) Return(_a0 string, _a1 error) *MockGitExecutor_DetermineWorktreePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_DetermineWorktreePath_Call) RunAndReturn(run func(string) (string, error)) *MockGitExecutor_DetermineWorktreePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommitDiff provides a mock function with given fields: hash
func (_m *MockGitExecutor) GetCommitDiff(hash string) (string, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetCommitDiff")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetCommitDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitDiff'
type MockGitExecutor_GetCommitDiff_Call struct {
	*mock.Call
}

// GetCommitDiff is a helper method to define mock.On call
//   - hash string
func (_e *MockGitExecutor_Expecter) GetCommitDiff(hash interface{}) *MockGitExecutor_GetCommitDiff_Call {
	return &MockGitExecutor_GetCommitDiff_Call{Call: _e.mock.On("GetCommitDiff", hash)}
}

func (_c *MockGitExecutor_GetCommitDiff_Call) Run(run func(hash string)) *MockGitExecutor_GetCommitDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_GetCommitDiff_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetCommitDiff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetCommitDiff_Call) RunAndReturn(run func(string) (string, error)) *MockGitExecutor_GetCommitDiff_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommitLog provides a mock function with given fields: limit
func (_m *MockGitExecutor) GetCommitLog(limit int) ([]git.CommitInfo, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetCommitLog")
	}

	var r0 []git.CommitInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]git.CommitInfo, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []git.CommitInfo); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]git.CommitInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetCommitLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitLog'
type MockGitExecutor_GetCommitLog_Call struct {
	*mock.Call
}

// GetCommitLog is a helper method to define mock.On call
//   - limit int
func (_e *MockGitExecutor_Expecter) GetCommitLog(limit interface{}) *MockGitExecutor_GetCommitLog_Call {
	return &MockGitExecutor_GetCommitLog_Call{Call: _e.mock.On("GetCommitLog", limit)}
}

func (_c *MockGitExecutor_GetCommitLog_Call) Run(run func(limit int)) *MockGitExecutor_GetCommitLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockGitExecutor_GetCommitLog_Call) Return(_a0 []git.CommitInfo, _a1 error) *MockGitExecutor_GetCommitLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetCommitLog_Call) RunAndReturn(run func(int) ([]git.CommitInfo, error)) *MockGitExecutor_GetCommitLog_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommitLogForRef provides a mock function with given fields: ref, limit
func (_m *MockGitExecutor) GetCommitLogForRef(ref string, limit int) ([]git.CommitInfo, error) {
	ret := _m.Called(ref, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetCommitLogForRef")
	}

	var r0 []git.CommitInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]git.CommitInfo, error)); ok {
		return rf(ref, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []git.CommitInfo); ok {
		r0 = rf(ref, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]git.CommitInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(ref, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetCommitLogForRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitLogForRef'
type MockGitExecutor_GetCommitLogForRef_Call struct {
	*mock.Call
}

// GetCommitLogForRef is a helper method to define mock.On call
//   - ref string
//   - limit int
func (_e *MockGitExecutor_Expecter) GetCommitLogForRef(ref interface{}, limit interface{}) *MockGitExecutor_GetCommitLogForRef_Call {
	return &MockGitExecutor_GetCommitLogForRef_Call{Call: _e.mock.On("GetCommitLogForRef", ref, limit)}
}

func (_c *MockGitExecutor_GetCommitLogForRef_Call) Run(run func(ref string, limit int)) *MockGitExecutor_GetCommitLogForRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockGitExecutor_GetCommitLogForRef_Call) Return(_a0 []git.CommitInfo, _a1 error) *MockGitExecutor_GetCommitLogForRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetCommitLogForRef_Call) RunAndReturn(run func(string, int) ([]git.CommitInfo, error)) *MockGitExecutor_GetCommitLogForRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentBranch provides a mock function with no fields
func (_m *MockGitExecutor) GetCurrentBranch() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentBranch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetCurrentBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentBranch'
type MockGitExecutor_GetCurrentBranch_Call struct {
	*mock.Call
}

// GetCurrentBranch is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) GetCurrentBranch() *MockGitExecutor_GetCurrentBranch_Call {
	return &MockGitExecutor_GetCurrentBranch_Call{Call: _e.mock.On("GetCurrentBranch")}
}

func (_c *MockGitExecutor_GetCurrentBranch_Call) Run(run func()) *MockGitExecutor_GetCurrentBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_GetCurrentBranch_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetCurrentBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetCurrentBranch_Call) RunAndReturn(run func() (string, error)) *MockGitExecutor_GetCurrentBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiff provides a mock function with given fields: ref
func (_m *MockGitExecutor) GetDiff(ref string) (string, error) {
	ret := _m.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for GetDiff")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(ref)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ref)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiff'
type MockGitExecutor_GetDiff_Call struct {
	*mock.Call
}

// GetDiff is a helper method to define mock.On call
//   - ref string
func (_e *MockGitExecutor_Expecter) GetDiff(ref interface{}) *MockGitExecutor_GetDiff_Call {
	return &MockGitExecutor_GetDiff_Call{Call: _e.mock.On("GetDiff", ref)}
}

func (_c *MockGitExecutor_GetDiff_Call) Run(run func(ref string)) *MockGitExecutor_GetDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_GetDiff_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetDiff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetDiff_Call) RunAndReturn(run func(string) (string, error)) *MockGitExecutor_GetDiff_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiffStat provides a mock function with given fields: ref
func (_m *MockGitExecutor) GetDiffStat(ref string) (string, error) {
	ret := _m.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for GetDiffStat")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(ref)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ref)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetDiffStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiffStat'
type MockGitExecutor_GetDiffStat_Call struct {
	*mock.Call
}

// GetDiffStat is a helper method to define mock.On call
//   - ref string
func (_e *MockGitExecutor_Expecter) GetDiffStat(ref interface{}) *MockGitExecutor_GetDiffStat_Call {
	return &MockGitExecutor_GetDiffStat_Call{Call: _e.mock.On("GetDiffStat", ref)}
}

func (_c *MockGitExecutor_GetDiffStat_Call) Run(run func(ref string)) *MockGitExecutor_GetDiffStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_GetDiffStat_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetDiffStat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetDiffStat_Call) RunAndReturn(run func(string) (string, error)) *MockGitExecutor_GetDiffStat_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileContent provides a mock function with given fields: path
func (_m *MockGitExecutor) GetFileContent(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContent")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContent'
type MockGitExecutor_GetFileContent_Call struct {
	*mock.Call
}

// GetFileContent is a helper method to define mock.On call
//   - path string
func (_e *MockGitExecutor_Expecter) GetFileContent(path interface{}) *MockGitExecutor_GetFileContent_Call {
	return &MockGitExecutor_GetFileContent_Call{Call: _e.mock.On("GetFileContent", path)}
}

func (_c *MockGitExecutor_GetFileContent_Call) Run(run func(path string)) *MockGitExecutor_GetFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_GetFileContent_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetFileContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetFileContent_Call) RunAndReturn(run func(string) (string, error)) *MockGitExecutor_GetFileContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileDiff provides a mock function with given fields: ref, path
func (_m *MockGitExecutor) GetFileDiff(ref string, path string) (string, error) {
	ret := _m.Called(ref, path)

	if len(ret) == 0 {
		panic("no return value specified for GetFileDiff")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(ref, path)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(ref, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(ref, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetFileDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileDiff'
type MockGitExecutor_GetFileDiff_Call struct {
	*mock.Call
}

// GetFileDiff is a helper method to define mock.On call
//   - ref string
//   - path string
func (_e *MockGitExecutor_Expecter) GetFileDiff(ref interface{}, path interface{}) *MockGitExecutor_GetFileDiff_Call {
	return &MockGitExecutor_GetFileDiff_Call{Call: _e.mock.On("GetFileDiff", ref, path)}
}

func (_c *MockGitExecutor_GetFileDiff_Call) Run(run func(ref string, path string)) *MockGitExecutor_GetFileDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGitExecutor_GetFileDiff_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetFileDiff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetFileDiff_Call) RunAndReturn(run func(string, string) (string, error)) *MockGitExecutor_GetFileDiff_Call {
	_c.Call.Return(run)
	return _c
}

// GetMainBranch provides a mock function with no fields
func (_m *MockGitExecutor) GetMainBranch() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMainBranch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetMainBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMainBranch'
type MockGitExecutor_GetMainBranch_Call struct {
	*mock.Call
}

// GetMainBranch is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) GetMainBranch() *MockGitExecutor_GetMainBranch_Call {
	return &MockGitExecutor_GetMainBranch_Call{Call: _e.mock.On("GetMainBranch")}
}

func (_c *MockGitExecutor_GetMainBranch_Call) Run(run func()) *MockGitExecutor_GetMainBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_GetMainBranch_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetMainBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetMainBranch_Call) RunAndReturn(run func() (string, error)) *MockGitExecutor_GetMainBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoRoot provides a mock function with no fields
func (_m *MockGitExecutor) GetRepoRoot() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepoRoot")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetRepoRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoRoot'
type MockGitExecutor_GetRepoRoot_Call struct {
	*mock.Call
}

// GetRepoRoot is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) GetRepoRoot() *MockGitExecutor_GetRepoRoot_Call {
	return &MockGitExecutor_GetRepoRoot_Call{Call: _e.mock.On("GetRepoRoot")}
}

func (_c *MockGitExecutor_GetRepoRoot_Call) Run(run func()) *MockGitExecutor_GetRepoRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_GetRepoRoot_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetRepoRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetRepoRoot_Call) RunAndReturn(run func() (string, error)) *MockGitExecutor_GetRepoRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetUntrackedFiles provides a mock function with no fields
func (_m *MockGitExecutor) GetUntrackedFiles() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUntrackedFiles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetUntrackedFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUntrackedFiles'
type MockGitExecutor_GetUntrackedFiles_Call struct {
	*mock.Call
}

// GetUntrackedFiles is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) GetUntrackedFiles() *MockGitExecutor_GetUntrackedFiles_Call {
	return &MockGitExecutor_GetUntrackedFiles_Call{Call: _e.mock.On("GetUntrackedFiles")}
}

func (_c *MockGitExecutor_GetUntrackedFiles_Call) Run(run func()) *MockGitExecutor_GetUntrackedFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_GetUntrackedFiles_Call) Return(_a0 []string, _a1 error) *MockGitExecutor_GetUntrackedFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetUntrackedFiles_Call) RunAndReturn(run func() ([]string, error)) *MockGitExecutor_GetUntrackedFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkingDirDiff provides a mock function with no fields
func (_m *MockGitExecutor) GetWorkingDirDiff() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWorkingDirDiff")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_GetWorkingDirDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkingDirDiff'
type MockGitExecutor_GetWorkingDirDiff_Call struct {
	*mock.Call
}

// GetWorkingDirDiff is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) GetWorkingDirDiff() *MockGitExecutor_GetWorkingDirDiff_Call {
	return &MockGitExecutor_GetWorkingDirDiff_Call{Call: _e.mock.On("GetWorkingDirDiff")}
}

func (_c *MockGitExecutor_GetWorkingDirDiff_Call) Run(run func()) *MockGitExecutor_GetWorkingDirDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_GetWorkingDirDiff_Call) Return(_a0 string, _a1 error) *MockGitExecutor_GetWorkingDirDiff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_GetWorkingDirDiff_Call) RunAndReturn(run func() (string, error)) *MockGitExecutor_GetWorkingDirDiff_Call {
	_c.Call.Return(run)
	return _c
}

// HasUncommittedChanges provides a mock function with no fields
func (_m *MockGitExecutor) HasUncommittedChanges() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasUncommittedChanges")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_HasUncommittedChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUncommittedChanges'
type MockGitExecutor_HasUncommittedChanges_Call struct {
	*mock.Call
}

// HasUncommittedChanges is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) HasUncommittedChanges() *MockGitExecutor_HasUncommittedChanges_Call {
	return &MockGitExecutor_HasUncommittedChanges_Call{Call: _e.mock.On("HasUncommittedChanges")}
}

func (_c *MockGitExecutor_HasUncommittedChanges_Call) Run(run func()) *MockGitExecutor_HasUncommittedChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_HasUncommittedChanges_Call) Return(_a0 bool, _a1 error) *MockGitExecutor_HasUncommittedChanges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_HasUncommittedChanges_Call) RunAndReturn(run func() (bool, error)) *MockGitExecutor_HasUncommittedChanges_Call {
	_c.Call.Return(run)
	return _c
}

// IsBareRepo provides a mock function with no fields
func (_m *MockGitExecutor) IsBareRepo() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsBareRepo")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_IsBareRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBareRepo'
type MockGitExecutor_IsBareRepo_Call struct {
	*mock.Call
}

// IsBareRepo is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) IsBareRepo() *MockGitExecutor_IsBareRepo_Call {
	return &MockGitExecutor_IsBareRepo_Call{Call: _e.mock.On("IsBareRepo")}
}

func (_c *MockGitExecutor_IsBareRepo_Call) Run(run func()) *MockGitExecutor_IsBareRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_IsBareRepo_Call) Return(_a0 bool, _a1 error) *MockGitExecutor_IsBareRepo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_IsBareRepo_Call) RunAndReturn(run func() (bool, error)) *MockGitExecutor_IsBareRepo_Call {
	_c.Call.Return(run)
	return _c
}

// IsDetachedHead provides a mock function with no fields
func (_m *MockGitExecutor) IsDetachedHead() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDetachedHead")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_IsDetachedHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDetachedHead'
type MockGitExecutor_IsDetachedHead_Call struct {
	*mock.Call
}

// IsDetachedHead is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) IsDetachedHead() *MockGitExecutor_IsDetachedHead_Call {
	return &MockGitExecutor_IsDetachedHead_Call{Call: _e.mock.On("IsDetachedHead")}
}

func (_c *MockGitExecutor_IsDetachedHead_Call) Run(run func()) *MockGitExecutor_IsDetachedHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_IsDetachedHead_Call) Return(_a0 bool, _a1 error) *MockGitExecutor_IsDetachedHead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_IsDetachedHead_Call) RunAndReturn(run func() (bool, error)) *MockGitExecutor_IsDetachedHead_Call {
	_c.Call.Return(run)
	return _c
}

// IsGitRepo provides a mock function with no fields
func (_m *MockGitExecutor) IsGitRepo() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsGitRepo")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockGitExecutor_IsGitRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGitRepo'
type MockGitExecutor_IsGitRepo_Call struct {
	*mock.Call
}

// IsGitRepo is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) IsGitRepo() *MockGitExecutor_IsGitRepo_Call {
	return &MockGitExecutor_IsGitRepo_Call{Call: _e.mock.On("IsGitRepo")}
}

func (_c *MockGitExecutor_IsGitRepo_Call) Run(run func()) *MockGitExecutor_IsGitRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_IsGitRepo_Call) Return(_a0 bool) *MockGitExecutor_IsGitRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitExecutor_IsGitRepo_Call) RunAndReturn(run func() bool) *MockGitExecutor_IsGitRepo_Call {
	_c.Call.Return(run)
	return _c
}

// IsOnMainBranch provides a mock function with no fields
func (_m *MockGitExecutor) IsOnMainBranch() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsOnMainBranch")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_IsOnMainBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOnMainBranch'
type MockGitExecutor_IsOnMainBranch_Call struct {
	*mock.Call
}

// IsOnMainBranch is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) IsOnMainBranch() *MockGitExecutor_IsOnMainBranch_Call {
	return &MockGitExecutor_IsOnMainBranch_Call{Call: _e.mock.On("IsOnMainBranch")}
}

func (_c *MockGitExecutor_IsOnMainBranch_Call) Run(run func()) *MockGitExecutor_IsOnMainBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_IsOnMainBranch_Call) Return(_a0 bool, _a1 error) *MockGitExecutor_IsOnMainBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_IsOnMainBranch_Call) RunAndReturn(run func() (bool, error)) *MockGitExecutor_IsOnMainBranch_Call {
	_c.Call.Return(run)
	return _c
}

// IsWorktree provides a mock function with no fields
func (_m *MockGitExecutor) IsWorktree() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsWorktree")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_IsWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWorktree'
type MockGitExecutor_IsWorktree_Call struct {
	*mock.Call
}

// IsWorktree is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) IsWorktree() *MockGitExecutor_IsWorktree_Call {
	return &MockGitExecutor_IsWorktree_Call{Call: _e.mock.On("IsWorktree")}
}

func (_c *MockGitExecutor_IsWorktree_Call) Run(run func()) *MockGitExecutor_IsWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_IsWorktree_Call) Return(_a0 bool, _a1 error) *MockGitExecutor_IsWorktree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_IsWorktree_Call) RunAndReturn(run func() (bool, error)) *MockGitExecutor_IsWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function with no fields
func (_m *MockGitExecutor) ListBranches() ([]git.BranchInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []git.BranchInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]git.BranchInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []git.BranchInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]git.BranchInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockGitExecutor_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) ListBranches() *MockGitExecutor_ListBranches_Call {
	return &MockGitExecutor_ListBranches_Call{Call: _e.mock.On("ListBranches")}
}

func (_c *MockGitExecutor_ListBranches_Call) Run(run func()) *MockGitExecutor_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_ListBranches_Call) Return(_a0 []git.BranchInfo, _a1 error) *MockGitExecutor_ListBranches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_ListBranches_Call) RunAndReturn(run func() ([]git.BranchInfo, error)) *MockGitExecutor_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorktrees provides a mock function with no fields
func (_m *MockGitExecutor) ListWorktrees() ([]git.WorktreeInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListWorktrees")
	}

	var r0 []git.WorktreeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]git.WorktreeInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []git.WorktreeInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]git.WorktreeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitExecutor_ListWorktrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorktrees'
type MockGitExecutor_ListWorktrees_Call struct {
	*mock.Call
}

// ListWorktrees is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) ListWorktrees() *MockGitExecutor_ListWorktrees_Call {
	return &MockGitExecutor_ListWorktrees_Call{Call: _e.mock.On("ListWorktrees")}
}

func (_c *MockGitExecutor_ListWorktrees_Call) Run(run func()) *MockGitExecutor_ListWorktrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_ListWorktrees_Call) Return(_a0 []git.WorktreeInfo, _a1 error) *MockGitExecutor_ListWorktrees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitExecutor_ListWorktrees_Call) RunAndReturn(run func() ([]git.WorktreeInfo, error)) *MockGitExecutor_ListWorktrees_Call {
	_c.Call.Return(run)
	return _c
}

// PruneWorktrees provides a mock function with no fields
func (_m *MockGitExecutor) PruneWorktrees() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PruneWorktrees")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitExecutor_PruneWorktrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneWorktrees'
type MockGitExecutor_PruneWorktrees_Call struct {
	*mock.Call
}

// PruneWorktrees is a helper method to define mock.On call
func (_e *MockGitExecutor_Expecter) PruneWorktrees() *MockGitExecutor_PruneWorktrees_Call {
	return &MockGitExecutor_PruneWorktrees_Call{Call: _e.mock.On("PruneWorktrees")}
}

func (_c *MockGitExecutor_PruneWorktrees_Call) Run(run func()) *MockGitExecutor_PruneWorktrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitExecutor_PruneWorktrees_Call) Return(_a0 error) *MockGitExecutor_PruneWorktrees_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitExecutor_PruneWorktrees_Call) RunAndReturn(run func() error) *MockGitExecutor_PruneWorktrees_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorktree provides a mock function with given fields: path
func (_m *MockGitExecutor) RemoveWorktree(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorktree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitExecutor_RemoveWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorktree'
type MockGitExecutor_RemoveWorktree_Call struct {
	*mock.Call
}

// RemoveWorktree is a helper method to define mock.On call
//   - path string
func (_e *MockGitExecutor_Expecter) RemoveWorktree(path interface{}) *MockGitExecutor_RemoveWorktree_Call {
	return &MockGitExecutor_RemoveWorktree_Call{Call: _e.mock.On("RemoveWorktree", path)}
}

func (_c *MockGitExecutor_RemoveWorktree_Call) Run(run func(path string)) *MockGitExecutor_RemoveWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitExecutor_RemoveWorktree_Call) Return(_a0 error) *MockGitExecutor_RemoveWorktree_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitExecutor_RemoveWorktree_Call) RunAndReturn(run func(string) error) *MockGitExecutor_RemoveWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitExecutor creates a new instance of MockGitExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitExecutor {
	mock := &MockGitExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
