// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/zjrosen/perles/internal/orchestration/client"
)

// MockAgentProvider is an autogenerated mock type for the AgentProvider type
type MockAgentProvider struct {
	mock.Mock
}

type MockAgentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentProvider) EXPECT() *MockAgentProvider_Expecter {
	return &MockAgentProvider_Expecter{mock: &_m.Mock}
}

// Client provides a mock function with no fields
func (_m *MockAgentProvider) Client() (client.HeadlessClient, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 client.HeadlessClient
	var r1 error
	if rf, ok := ret.Get(0).(func() (client.HeadlessClient, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() client.HeadlessClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.HeadlessClient)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentProvider_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockAgentProvider_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockAgentProvider_Expecter) Client() *MockAgentProvider_Client_Call {
	return &MockAgentProvider_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockAgentProvider_Client_Call) Run(run func()) *MockAgentProvider_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentProvider_Client_Call) Return(_a0 client.HeadlessClient, _a1 error) *MockAgentProvider_Client_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentProvider_Client_Call) RunAndReturn(run func() (client.HeadlessClient, error)) *MockAgentProvider_Client_Call {
	_c.Call.Return(run)
	return _c
}

// Extensions provides a mock function with no fields
func (_m *MockAgentProvider) Extensions() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extensions")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockAgentProvider_Extensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extensions'
type MockAgentProvider_Extensions_Call struct {
	*mock.Call
}

// Extensions is a helper method to define mock.On call
func (_e *MockAgentProvider_Expecter) Extensions() *MockAgentProvider_Extensions_Call {
	return &MockAgentProvider_Extensions_Call{Call: _e.mock.On("Extensions")}
}

func (_c *MockAgentProvider_Extensions_Call) Run(run func()) *MockAgentProvider_Extensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentProvider_Extensions_Call) Return(_a0 map[string]interface{}) *MockAgentProvider_Extensions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentProvider_Extensions_Call) RunAndReturn(run func() map[string]interface{}) *MockAgentProvider_Extensions_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockAgentProvider) Type() client.ClientType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 client.ClientType
	if rf, ok := ret.Get(0).(func() client.ClientType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(client.ClientType)
	}

	return r0
}

// MockAgentProvider_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockAgentProvider_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockAgentProvider_Expecter) Type() *MockAgentProvider_Type_Call {
	return &MockAgentProvider_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockAgentProvider_Type_Call) Run(run func()) *MockAgentProvider_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentProvider_Type_Call) Return(_a0 client.ClientType) *MockAgentProvider_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentProvider_Type_Call) RunAndReturn(run func() client.ClientType) *MockAgentProvider_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentProvider creates a new instance of MockAgentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentProvider {
	mock := &MockAgentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
