with-expecter: true
dir: internal/mocks
outpkg: mocks
packages:
  github.com/zjrosen/perles/internal/beads:
    interfaces:
      BeadsClient:
      BeadsExecutor:
  github.com/zjrosen/perles/internal/bql:
    interfaces:
      BQLExecutor:
  github.com/zjrosen/perles/internal/cachemanager:
    interfaces:
      CacheManager:
  github.com/zjrosen/perles/internal/mode/shared:
    interfaces:
      Clock:
      Clipboard:
  github.com/zjrosen/perles/internal/orchestration/client:
    interfaces:
      HeadlessClient:
      HeadlessProcess:
